version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: 'app'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # exposed:inside_container
      - '3308:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'

  etl:
    build: ./services/etl
    volumes:
      - ./services/etl:/etl
    command: python3 scrape.py
